# Nama workflow yang akan muncul di tab "Actions" GitHub
name: Build and Test Automation Project

# Konfigurasi pemicu (trigger) workflow
on:
  push:
    branches: [ "main" ]  # Berjalan saat ada push ke branch main
  pull_request:
    branches: [ "main" ]  # Berjalan saat ada pull request ke branch main

# Daftar pekerjaan (jobs) yang akan dijalankan
jobs:
  build-and-test:
    # Menentukan environment atau sistem operasi yang digunakan
    # "ubuntu-latest" adalah pilihan yang umum dan stabil
    runs-on: ubuntu-latest

    # Langkah-langkah (steps) yang akan dieksekusi secara berurutan
    steps:
      # Langkah 1: Mengunduh kode dari repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Langkah 2: Menyiapkan environment Java (JDK)
      # Ganti '17' dengan versi Java yang kamu gunakan jika berbeda
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # Langkah 3: Memberikan izin eksekusi pada gradlew
      # Ini penting agar GitHub Actions bisa menjalankan perintah Gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Langkah 4: Menjalankan tes API
      # Perintah ini menjalankan semua tes yang ada di proyek
      - name: Run API Tests
        run: ./gradlew test

      # Langkah 5: Menjalankan tes UI Web
      # Catatan: Jika tes UI membutuhkan browser, perlu konfigurasi tambahan.
      # Asumsi untuk saat ini tes UI bisa dijalankan dengan perintah yang sama.
      - name: Run Web UI Tests
        run: ./gradlew test  # Ganti dengan task Gradle spesifik jika ada

      # Langkah 6: Mengunggah laporan hasil pengujian (artefak)
      # Laporan ini bisa diunduh setelah workflow selesai
      - name: Upload test reports
        # Langkah ini akan selalu berjalan, meskipun tes gagal
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: build/reports/tests/test # Path menuju folder laporan hasil tes